// js/event_transformer.js
// Module: Transforms an array of parsed ICS events into a simplified JSON structure and handles file export.
// Exports: transformEvents(events), exportEventsToJsonFile(events, directory, filename)

const fs = require('fs'); // Required for file system operations (Node.js environment)

/**
 * Transforms parsed event data into a simple JSON structure, focusing on core fields.
 *
 * @param {Array<Object>} events - Array of event objects generated by parser.js.
 * @returns {Array<Object>} - Array of standardized event objects.
 */
function transformEvents(events) {
    if (!events || events.length === 0) {
        return [];
    }

    const transformedData = events.map(ev => {
        let startDateStr = '';
        let startTimeStr = '';
        let endTimeStr = '';

        // Helper function to extract date and time from a Date object
        const extractDateTime = (parsedObj) => {
            if (parsedObj && parsedObj.date instanceof Date) {
                // Formatting options for Date and Time
                const dateOptions = { year: 'numeric', month: '2-digit', day: '2-digit' };
                const timeOptions = { hour: '2-digit', minute: '2-digit', hour12: false };
                
                // Use en-US locale for consistent formatting (MM/DD/YYYY)
                const locale = 'en-US';
                // Apply Pacific Time Zone (Oregon/Los Angeles)
                const timeZone = 'America/Los_Angeles'; 
                
                const dateStr = parsedObj.date.toLocaleDateString(locale, { ...dateOptions, timeZone });
                const timeStr = parsedObj.date.toLocaleTimeString(locale, { ...timeOptions, timeZone });
                return { date: dateStr, time: timeStr };
            }
            // Case for date-only events (VALUE=DATE)
            if (parsedObj && parsedObj.type === 'date') {
                return { date: parsedObj.isoDate || parsedObj.original, time: 'All Day' };
            }
            return { date: '', time: '' };
        };

        const start = extractDateTime(ev._parsed.DTSTART);
        const end = extractDateTime(ev._parsed.DTEND);

        // Handle date-only event
        if (start.time === 'All Day') {
            startDateStr = start.date;
            startTimeStr = '00:00';
            endTimeStr = '23:59';
            if (end.date && end.date !== start.date) {
                 // DTEND is a different date (date-only event). For simplicity, we prioritize DTSTART date.
            }
        } else {
            startDateStr = start.date;
            startTimeStr = start.time;
            endTimeStr = end.time;
        }

        return {
            summary: ev.SUMMARY || '',
            date: startDateStr,
            time_start: startTimeStr,
            time_end: endTimeStr,
            status: ev.STATUS || 'TENTATIVE', // e.g., CONFIRMED, TENTATIVE, CANCELLED
            // Replace potential HTML breaks with newline characters for clean display
            description: ev.DESCRIPTION ? ev.DESCRIPTION.replace(/<br>/g, '\n') : '' 
        };
    });

    return transformedData;
}

/**
 * Writes the transformed event data array to a JSON file.
 * NOTE: This function requires a Node.js environment due to the use of 'fs'.
 * * @param {Array<Object>} events - Array of standardized event objects.
 * @param {string} directory - The directory path (e.g., 'data').
 * @param {string} filename - The file name (e.g., 'w2w-data.json').
 */
function exportEventsToJsonFile(events, directory, filename) {
    try {
        const filePath = `${directory}/${filename}`;
        const jsonContent = JSON.stringify(events, null, 2); // Use 2 spaces for pretty printing

        // Check if the directory exists, and create it if it doesn't
        if (!fs.existsSync(directory)) {
            fs.mkdirSync(directory, { recursive: true });
            console.log(`Directory created: ${directory}`);
        }

        // Write the JSON content to the file
        fs.writeFileSync(filePath, jsonContent, 'utf8');
        console.log(`Successfully exported data to: ${filePath}`);

    } catch (error) {
        console.error("Error writing JSON file:", error);
    }
}

/* ---------- Export ---------- */
module.exports = {
    transformEvents,
    exportEventsToJsonFile
};

/* // Example Usage demonstrating both transformation and export:
const { parseICS } = require('./parser'); 
// NOTE: This file assumes the existence of 'parser.js' and requires a Node.js environment.

const icsTextExample = `
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Example//NONSGML Demo Calendar//EN
BEGIN:VEVENT
UID:19970901T130000Z-123401@example.com
DTSTAMP:19970901T130000Z
DTSTART:20251120T100000Z 
DTEND:20251120T113000Z
STATUS:CONFIRMED
SUMMARY:Q4 Project Report
DESCRIPTION:Prepare presentation slides and business figures.
LOCATION:5th Floor Meeting Room
END:VEVENT
END:VCALENDAR
`;

const events = parseICS(icsTextExample); 
const simpleData = transformEvents(events);

// The actual call to export the file:
exportEventsToJsonFile(simpleData, 'data', 'w2w-data.json'); 
*/